### ISSUE TITLE
What happened to the GTAV integration?

### ISSUE THREAD

**Issue by louh** [openai/universe#160] opened 2017-03-02 21:22 UTC
The original blog post (https://openai.com/blog/GTA-V-plus-Universe/) is gone, but there's no explanation why?

**Comment by tlbtlbtlb** [comment] 2017-03-03 03:57
Dupe of https://github.com/openai/universe/issues/126. (No resolution on licensing issues yet).

**Closed by tlbtlbtlb** 2017-03-03 03:57 UTC
